# Working with APIs

### Converting API into DataFrame

In [1]:
import pandas as pd
import requests

Hitting the server with this api

In [2]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [ ]:
response  # 200 - good, 404 - not found, 500 - server error

Making tempary dataframe for 1 page of json response outoff 426 pages which I know coz, I checked on website known as jsonviewer for better visualiztion my json file.

Extracting imp cols only

In [4]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [7]:
temp_df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,46.0482,8.717,29975
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,36.2695,8.687,22647
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,20.7597,8.572,13716
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,22.4777,8.567,17237
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,16.2894,8.600,9833
5,1181678,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",2023-09-21,7.6197,8.536,303
6,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,26.8686,8.534,18088
7,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,29.7555,8.528,35365
8,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,9.0525,8.517,4566
9,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,21.5277,8.505,18983
10,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,30.5539,8.495,26213
11,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,26.2811,8.494,20308
12,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,24.8779,8.486,29864
13,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,21.8903,8.500,12365
14,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,46.7159,8.468,39190
15,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-23,19.1901,8.467,9499
16,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,23.6969,8.463,29413
17,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,20.8282,8.452,14133
18,346,Seven Samurai,A samurai answers a village's request for prot...,1954-04-26,11.6577,8.451,4148
19,12477,Grave of the Fireflies,"In the final months of World War II, 14-year-o...",1988-04-16,0.0100,8.444,6415

Create empty dataframe for storing all pages, So we use loop for it

In [9]:
df = pd.DataFrame()

In [10]:
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = df.append(temp_df,ignore_index=True)

In [21]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,18.433,8.7,2763
1,724089,Gabriel's Inferno Part II,Professor Gabriel Emerson finally learns the t...,2020-07-31,8.439,8.7,1223
2,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,65.570,8.7,18637
3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,63.277,8.7,14052
4,761053,Gabriel's Inferno Part III,The final part of the film adaption of the ero...,2020-11-19,26.691,8.7,773
...,...,...,...,...,...,...,...
8546,13805,Disaster Movie,"The filmmaking team behind the hits ""Scary Mov...",2008-08-29,14.630,3.2,714
8547,5491,Battlefield Earth,"In the year 3000, man is no match for the Psyc...",2000-05-12,10.647,3.0,543
8548,14164,Dragonball Evolution,The young warrior Son Goku sets out on a quest...,2009-03-12,32.244,2.8,1447
8549,11059,House of the Dead,"Set on an island off the coast, a techno rave ...",2003-04-11,14.502,2.8,238
8550,40016,Birdemic: Shock and Terror,A platoon of eagles and vultures attacks the r...,2010-02-27,9.824,2.2,215

In [ ]:
df.shape

To export this dataframe in CSV form

In [23]:
df.to_csv('movies.csv')

You can now upload this dataset on kaggle and become dataset master.

##### NOTE : For free apis go to RAPID API